operationId: apps_get_logs_active_deployment

summary: Retrieve Active Deployment Logs

description: Retrieve the logs of the active deployment if one exists. The 
  response will include links to either real-time logs of an in-progress or
  active deployment or archived logs of a past deployment. Note log_type=BUILD
  logs will return logs associated with the current active deployment (being
  served). To view build logs associated with in-progress build, the query must
  explicitly reference the deployment id. 

tags:
- Apps

parameters:
  - $ref: parameters.yml#/app_id
  - $ref: parameters.yml#/component
  - $ref: parameters.yml#/live_updates
  - $ref: parameters.yml#/log_type
  - $ref: parameters.yml#/time_wait

responses:
  "200":
    $ref: responses/list_logs.yml

  "401":
    $ref: ../../shared/responses/unauthorized.yml

  '404':
    $ref: '../../shared/responses/not_found.yml'

  "429":
    $ref: "../../shared/responses/too_many_requests.yml"

  "500":
    $ref: ../../shared/responses/server_error.yml

  default:
    $ref: ../../shared/responses/unexpected_error.yml

x-codeSamples:
  - $ref: 'examples/curl/apps_get_logs_active_deployment.yml'

security:
  - bearer_auth:
    - 'read'

