type: object

properties:
  meta:
    description: Information about the response itself.
    type: object
    properties:
      total:
        description: Number of objects returned by the request.
        type: integer
        example: 1

    required:
      - total

required:
  - meta
