lang: Python
source: |-
  import os
  from pydo import Client

  client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))

  create_resp = client.apps.create_deployment(app_id="b6bdf840", body={"force_build": True})