extends:
  - [spectral:oas, all]
  - ./spectral/ruleset.yml

functionsDir: ./spectral/functions

functions:
  - ensurePropertiesExample
  - ensureAllArraysHaveItemTypes

rules:
  contact-properties: off
  operation-default-response: off
  operation-singular-tag: off
