openapi: 3.0.0
info:
  title: DigitalOcean API
  version: '2.0'
  description: 'The DigitalOcean API allows you to manage Droplets and resources within the DigitalOcean cloud in a simple, programmatic way using conventional HTTP requests.'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: DigitalOcean API Team
    email: api-engineering@digitalocean.com
  termsOfService: 'https://www.digitalocean.com/legal/terms-of-service-agreement/'
servers:
  - url: 'https://api.digitalocean.com/v2'
    description: production
tags:
  - name: Account
    description: Provides information about your current account.
  - name: SSH Keys
    description: Manage SSH keys available on your account.
paths:
  /account:
    $ref: 'endpoints/account.yml'
  /account/keys:
    $ref: 'endpoints/ssh_keys.yml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
