operationId: get_database_config

summary: Retrieve Configuration for an Existing Database

description: |
  To show configuration parameters for an existing database cluster, send a GET request to
  `/v2/databases/$DATABASE_ID/config`.

  **Note:** Database config is not yet supported for Redis and Postgres clusters.

  The response will be a JSON object with a `config` key. This will be set to an object
  containing any extra database configuration.

tags:
  - Databases

parameters:
  - $ref: 'parameters.yml#/database_cluster_uuid'

responses:
  '200':
    $ref: 'responses/database_config.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/get_database_config.yml'
  - $ref: 'examples/go/get_database.yml'
