operationId: patch_database_config

summary: Change configuration values

description: |
  To update configuration for an existing database cluster, send a PATCH request to
  `/v2/databases/$DATABASE_ID/config`.

  Note: Database configuration is not supported for Redis and Postgres clusters.

tags:
  - Databases

requestBody:
  required: true
  content:
    application/json:
      schema:
        allOf:
          - $ref: 'models/database_config.yml'
          - type: object

parameters:
  - $ref: 'parameters.yml#/database_cluster_uuid'

responses:
  '200':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/get_database.yml'
  - $ref: 'examples/go/get_database.yml'
