type: object
nullable: true
description: An object specifying whether the Peer-to-peer OCI registry component should be enabled for the Kubernetes cluster.
properties:
  enabled:
    type: boolean
    description: Indicates whether the Peer-to-peer OCI registry component is enabled.
    example: true
