type: object

properties:
  connection_timeout:
    type: integer
    format: uint32  
    example: 28800
    description: The number of seconds mysql server will wait for connect packets.
  default_time_zone:
    type: string
    example: 'UTC'
    description: The time zone mysql will use for zone-sensitive time values.
  innodb_log_buffer_size:
    type: integer
    format: uint64
  innodb_online_alter_log_max_size:
    type: integer
    format: unit64
  innodby_lock_wait_timeout:
    type: integer
    format: uint32
  interative_timeout:
    type: integer
    format: uint32
  max_allowed_packet:
    type: integer
    format: unit64
  read_timeout:
    type: integer
    format: uint32
  sort_buffer_size:
    type: integer
    format: uint64
  sql_mode:
    type: string
  sql_require_primary_key:
    type: bool
  wait_timeout:
    type: integer
    format: uint32 
  write_timeout:
    type: integer
    format: uint32
