description: >-
  The result will be a JSON object with an action key. 
  This will be set to an action object containing the standard action attributes.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      properties:
        action:
          $ref: '../models/action.yml'