description: A JSON of the requested deployment

content:
  application/json:
    schema:
      $ref: ../models/apps_deployment_response.yml
    examples:
      deployment:
        $ref: examples.yml#/deployment

headers:
  ratelimit-limit:
    $ref: ../../../shared/headers.yml#/ratelimit-limit
  ratelimit-remaining:
    $ref: ../../../shared/headers.yml#/ratelimit-remaining
  ratelimit-reset:
    $ref: ../../../shared/headers.yml#/ratelimit-reset
