lang: Python
source: |-
  import os
  from pydo import Client

  client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))

  resp = client.databases.get_do_settings(database_cluster_uuid="9cc10173-e9ea-4176-9dbc-a4cee4c4ff30")
