lang: Python
source: |-
  import os
  from pydo import Client

  client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))

  resp = client.kubernetes.delete_node(cluster_id="da8fda8", node_pool_id="a8f3da", node_id="fa09daf")
