lang: Python
source: |-
  import os
  from pydo import Client

  client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))

  req = {
    "cluster_uuids": [
      "bd5f5959-5e1e-4205-a714-a914373942af",
      "50c2f44c-011d-493e-aee5-361a4a0d1844"
    ]
  }

  resp = client.kubernetes.add_registry(body=req)
