lang: Python
source: |-
  import os
  from pydo import Client

  client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))

  req = {
    "name": "prod-cluster-01",
    "region": "nyc1",
    "version": "1.18.6-do.0",
    "node_pools": [
      {
        "size": "s-1vcpu-2gb",
        "count": 3,
        "name": "worker-pool"
      }
    ]
  }

  resp = client.kubernetes.create_cluster(body=req)
