lang: Python
source: |-
  import os
  from pydo import Client

  client = Client(token=os.environ.get("DIGITALOCEAN_TOKEN"))

  resp = client.kubernetes.list_associated_resources(cluster_id="da8fda8")
