lang: Go
source: |-
  import (
      "context"
      "os"

      "github.com/digitalocean/godo"
  )

  func main() {
      token := os.Getenv("DIGITALOCEAN_TOKEN")

      client := godo.NewFromToken(token)
      ctx := context.TODO()

      credentials, _, err := client.Kubernetes.GetCredentials(ctx, "bd5f5959-5e1e-4205-a714-a914373942af")
  }
