lang: Go
source: |-
  import (
      "context"
      "os"

      "github.com/digitalocean/godo"
  )

  func main() {
      token := os.Getenv("DIGITALOCEAN_TOKEN")

      client := godo.NewFromToken(token)
      ctx := context.TODO()

      options, _, err := client.Kubernetes.GetOptions(ctx)
  }
