lang: Go
source: |-
  import (
      "context"
      "os"

      "github.com/digitalocean/godo"
  )

  func main() {
      token := os.Getenv("DIGITALOCEAN_TOKEN")

      client := godo.NewFromToken(token)
      ctx := context.TODO()

      dbID := "9cc10173-e9ea-4176-9dbc-a4cee4c4ff30"

      req := godo.DatabaseUpdateDOSettingsRequest{
          DOSettings: &godo.DOSettings{
              ServiceCnames: []string{
                  "db.example.com",
                  "db-replica.example.com",
              },
          },
      }
      _, err := client.Databases.UpdateDOSettings(ctx, dbID, &req)
  }
