id:
  in: path
  name: id
  description: A unique identifier for a vector database.
  required: true
  example: 9cc10173-e9ea-4176-9dbc-a4cee4c4ff30
  schema:
    type: string

backup_id:
  in: path
  name: backup_id
  description: A unique identifier for a vector database backup.
  required: true
  example: vectordb-9cc10173-e9ea-4176-9dbc-a4cee4c4ff30-20240101-120000
  schema:
    type: string
