lang: cURL
source: |-
  curl -X PUT \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
    -d '{"do_settings": {"service_cnames": ["db.example.com", "db-replica.example.com"]}}' \
    "https://api.digitalocean.com/v2/databases/9cc10173-e9ea-4176-9dbc-a4cee4c4ff30/do_settings"
