type: object
required:
  - endpoint
properties:
  credentials:
    type: object
    description: "credentials for Opensearch cluster user. Optional if `cluster_uuid` is passed."
    properties:
      username:
        type: string
        example: "username"
      password:
        type: string
        example: "password"
  endpoint:
    type: string
    example: "example.com"
    description: "host of the Opensearch cluster"
  cluster_uuid:
    type: string
    example: "85148069-7e35-4999-80bd-6fa1637ca385"
    description: "Uuid of managed Opensearch cluster"
  cluster_name:
    type: string
    example: "managed_dbaas_cluster"
    description: "Name of managed Opensearch cluster"
  index_name:
    type: string
    description: "Opensearch index to send logs"
    example: "logs"
  retention_days:
    type: integer
    description: "Number of days to retain logs in Opensearch (default: 14)"
    example: 14


