app_slug:
  name: app_slug
  in: path
  description: The slug identifier for an application.
  required: true
  schema:
    type: string
  example: example-app

resource_uuid:
  name: resource_uuid
  in: path
  description: A unique identifier for the add-on resource.
  required: true
  schema:
    type: string
    format: uuid
  example: "4de7ac8b-495b-4884-9a69-1050c6793cd6"
