lang: Ruby
source: |-
  require 'droplet_kit'
  token = ENV['DIGITALOCEAN_TOKEN']
  client = DropletKit::Client.new(access_token: token)

  node_pools = client.kubernetes_clusters.node_pools(id: 'bd5f5959-5e1e-4205-a714-a914373942af')
  node_pools.each
