operationId: kubernetes_recycle_node_pool

deprecated: true

summary: Recycle a Kubernetes Node Pool

description: |
  The endpoint has been deprecated. Please use the DELETE
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/node_pools/$NODE_POOL_ID/nodes/$NODE_ID`
  method instead.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'
  - $ref: 'parameters.yml#/kubernetes_node_pool_id'

requestBody:
  required: true

  content:
    application/json:
      schema:
        properties:
          nodes:
            type: array
            items:
              type: string
            example:
            - d8db5e1a-6103-43b5-a7b3-8a948210a9fc

responses:
  '202':
    $ref: '../../shared/responses/accepted.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'
security:
  - bearer_auth:
    - 'write'
