operationId: kubernetes_update_nodePool

summary: Update a Node Pool in a Kubernetes Cluster

description: |
  To update the name of a node pool, edit the tags applied to it, or adjust its
  number of nodes, send a PUT request to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/node_pools/$NODE_POOL_ID` with the
  following attributes.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'
  - $ref: 'parameters.yml#/kubernetes_node_pool_id'

requestBody:
  required: true

  content:
    application/json:
      schema:
        $ref: 'models/node_pool.yml#/kubernetes_node_pool_update'

responses:
  '202':
    $ref: 'responses/node_pool_update.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_update_nodePool.yml'
  - $ref: 'examples/go/kubernetes_update_nodePool.yml'
  - $ref: 'examples/ruby/kubernetes_update_nodePool.yml'

security:
  - bearer_auth:
    - 'write'
