operationId: kubernetes_add_registries

summary: Add Container Registries to Kubernetes Clusters

description: To integrate the container registries with Kubernetes clusters, send
  a POST request to `/v2/kubernetes/registries`.

tags:
  - Kubernetes

requestBody:
  content:
    application/json:
      schema:
        $ref: 'models/cluster_registries.yml'

responses:
  '204':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_add_registries.yml'

security:
  - bearer_auth:
    - 'kubernetes:create'
    - 'kubernetes:update'
