operationId: kubernetes_list_options

summary: List Available Regions, Node Sizes, and Versions of Kubernetes

description: To list the versions of Kubernetes available for use, the regions
  that support Kubernetes, and the available node sizes, send a GET request to
  `/v2/kubernetes/options`.

tags:
  - Kubernetes

responses:
  '200':
    $ref: 'responses/all_options.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_list_options.yml'
  - $ref: 'examples/go/kubernetes_list_options.yml'
  - $ref: 'examples/ruby/kubernetes_list_options.yml'

security:
  - bearer_auth:
    - 'read'

