operationId: kubernetes_destroy_associatedResourcesSelective

summary: Selectively Delete a Cluster and its Associated Resources

description: |
  To delete a Kubernetes cluster along with a subset of its associated resources,
  send a DELETE request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/destroy_with_associated_resources/selective`.

  The JSON body of the request should include `load_balancers`, `volumes`, or
  `volume_snapshots` keys each set to an array of IDs for the associated
  resources to be destroyed.

  The IDs can be found by querying the cluster's associated resources endpoint.
  Any associated resource not included in the request will remain and continue
  to accrue changes on your account.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

requestBody:
  required: true

  content:
    application/json:
      schema:
        $ref: 'models/associated_kubernetes_resources.yml#/destroy_associated_kubernetes_resources'

responses:
  '204':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_destroy_associatedResourcesSelective.yml'
  - $ref: 'examples/go/kubernetes_destroy_associatedResourcesSelective.yml'

security:
  - bearer_auth:
    - 'write'
