name: Trigger Python Client Generation
on:
  workflow_run:
    workflows: [Spec Main]
    types:
      - completed

jobs:
  build:
    name: Trigger digitalocean-client-python Workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name : Print Title of PR
        env:
            TITLE: ${{ github.event.pull_request.title }}
      - name: Check short sha outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Check pr title outputs
        run: echo $TITLE
      - name: trigger-workflow
        run: gh workflow run --repo danaelhe/pydo python-client-gen.yml --ref main -f openapi_short_sha=${{ steps.vars.outputs.sha_short }} pr_title=$TITLE
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
