name: Trigger Python Client Generation
on:
  workflow_run:
    workflows: [tagged-release]
    types:
      - completed

jobs:
  build:
    name: Trigger digitalocean-client-python Workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: trigger-workflow
        run: gh workflow run --repo danaelhe/digitalocean-client-python python-client-gen.yml --ref main -f release_version=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}