name: Trigger Python Client Generation
on: 
  push:
    branches:
      - main
    paths:
      - 'specification/**'
jobs:
  build:
    name: Trigger digitalocean-client-python Workflow
    runs-on: ubuntu-latest
    steps:
      - name: trigger-workflow
        run: gh workflow run --repo digitalocean/digitalocean-client-python python-client-gen.yml --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.OPENAPI_SECRET }}