name: Validate Client Generation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Check out openapi
        uses: actions/checkout@v2.5.0

      - name: Verify artifact
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-url
          path: ./artifact.txt
